Fix/i18n/m
RimlTempest/StampApp pull request #169
Opened 2021-07-16 13:46 UTC by keykimu

i18n対応しました。（利用規約、使い方、プライバシーポリシー以外）

2021-07-16 13:58 UTC, keykimu commented
![bandicam 2021-07-16 22-48-21-707](https://user-images.githubusercontent.com/44780741/125959072-035aa112-c978-481d-92ad-139d6d0a7117.jpg)
![bandicam 2021-07-16 22-48-39-239](https://user-images.githubusercontent.com/44780741/125959078-4a0f8766-4970-46ee-817b-198d11bcb356.jpg)
![bandicam 2021-07-16 22-48-55-959](https://user-images.githubusercontent.com/44780741/125959079-bf446ad5-fca5-428e-9e6e-25f91943bae0.jpg)
![bandicam 2021-07-16 22-49-09-652](https://user-images.githubusercontent.com/44780741/125959081-bcbf6f23-14fe-43c1-b31a-5dc8ac39a691.jpg)
![bandicam 2021-07-16 22-50-41-104](https://user-images.githubusercontent.com/44780741/125959084-234ab7f5-7f79-4ff5-a6b2-4fe0d53b638f.jpg)
![bandicam 2021-07-16 22-50-18-518](https://user-images.githubusercontent.com/44780741/125959083-e30b6845-d07b-4ad4-81e2-059f2e541d95.jpg)
![bandicam 2021-07-16 22-51-06-775](https://user-images.githubusercontent.com/44780741/125959088-e2ec178b-3455-4668-a069-55b929ac6925.jpg)
![bandicam 2021-07-16 22-52-50-064](https://user-images.githubusercontent.com/44780741/125959093-ed55aa6d-04be-41e7-8847-1ddbcef04a9f.jpg)
![bandicam 2021-07-16 22-53-12-875](https://user-images.githubusercontent.com/44780741/125959095-1d5f1883-34bd-4297-829c-906e2915e985.jpg)
![bandicam 2021-07-16 22-51-38-102](https://user-images.githubusercontent.com/44780741/125959089-1e940508-a712-4da5-b8ea-f836216f09d5.jpg)
![bandicam 2021-07-16 22-53-23-194](https://user-images.githubusercontent.com/44780741/125959100-51626486-65fa-4f42-9eb0-6abc2ce5f847.jpg)
![bandicam 2021-07-16 22-53-38-422](https://user-images.githubusercontent.com/44780741/125959103-4c12a624-c1d9-4096-bc22-ce9ae0f0e702.jpg)

2021-07-16 19:52 UTC, RimlTempest commented on lib/View/history.dart
> +  void init() {
initStateからinitに変えたのは何か理由がある感じ？

2021-07-16 19:53 UTC, RimlTempest commented on lib/View/history.dart
> +    return MaterialApp(
Scaffoldで統一しているのでMaterialAppにしないでください

2021-07-16 19:59 UTC, RimlTempest commented on lib/dbHelper.dart
このファイルi18n対応している部分がないので上げる必要ないです

2021-07-16 19:59 UTC, RimlTempest commented on lib/dbInterface.dart
>      final List<Map<String, dynamic>> maps = await db.rawQuery("SELECT * " +
同じくここもi18n対応していないので上げないでください

2021-07-16 20:00 UTC, RimlTempest commented on lib/l10n/app_en.arb
> +    "totalStamps":"Stamp total",
文字の長さ的に Total だけでいいかも

2021-07-16 20:02 UTC, RimlTempest commented on lib/models/stamp.dart
>    final DateTime getDate; // 取得日
これもi18n対応させる箇所がないので上げないでください

2021-07-16 20:06 UTC, RimlTempest commented on lib/l10n/app_en.arb
> +    "usageHistory":"Usage History",
key側は呼び出しているファイルでもわかりやすいようにアッパースネークケースで書いてくれたほうが親切だとおもうので修正のほうお願いします。

例)
"USEGE_HISTORY": "Usage History",

のような形で

2021-07-16 20:22 UTC, RimlTempest commented on lib/l10n/app_ja.arb
> +    "use":"利用",
gettingStampならuseはuseStampのほうが統一感がある気がする
日本語の部分もスタンプゲットならスタンプ利用のほうがいい

2021-07-16 20:25 UTC, RimlTempest commented on lib/l10n/app_en.arb
> +    "use":"use",
英語のほうもgettingに合わせてuse a Stampsが 妥当そう

2021-07-16 20:27 UTC, RimlTempest commented on lib/l10n/app_en.arb
> +    "usage":"Usage",
ニュアンス的に How to use the app のほうがよさげじゃないかな？

2021-07-16 20:30 UTC, RimlTempest commented on lib/l10n/app_en.arb
> +    "error":"error",
単一単語の場合、value側は頭を大文字にしたほうがよさそう

2021-07-16 20:31 UTC, RimlTempest commented on lib/l10n/app_en.arb
> +    "yes":"yes",
同じく単一単語

2021-07-17 03:02 UTC, keykimu commented on lib/View/history.dart
> +  void init() {
普通の関数として呼び出したいから

2021-07-17 06:09 UTC, RimlTempest commented on lib/View/history.dart
> +  void init() {
画面初期読み込み時に
```Dart
setItem();
_selectItem = _items[0].value;
```

を呼ぶようになってたはずだけどこれ普通に関数化しても正常に動くの？

2021-07-17 07:41 UTC, keykimu commented on lib/View/history.dart
> +  void init() {
動く

2021-07-17 08:01 UTC, keykimu commented on lib/l10n/app_en.arb
> +    "usage":"Usage",
設定項目だからなるべく一単語にしたつもりだけど修正するならするけどしたほうがいい？

2021-07-17 13:36 UTC, RimlTempest commented on lib/View/history.dart
> +  void init() {
関数化するとライフサイクルで回らず関数の呼び出す場所が動くたびに呼ばれるけどそれも問題ない？

2021-07-17 13:41 UTC, RimlTempest commented on lib/l10n/app_en.arb
> +    "usage":"Usage",
日本語だと使い方でぱっと見わかるけど英語でUsageだといろんな意味のとらえ方がでてくるので一単語ってより利用者が理解しやすい感じにしたほうがいいと思う

2021-07-17 17:08 UTC, keykimu commented on lib/View/history.dart
> +  void init() {
一通りスタンプ取得したり交換したりしたけど、問題なさそうだしたぶん大丈夫だと思う。

2021-07-20 00:43 UTC, RimlTempest requested changes
必要のないファイルを上げない

2021-07-20 00:52 UTC, zinNORI commented on lib/l10n/app_en.arb
> +    "dataIsIncorrect":"Data is incorrect.",
こっちだった
QR data is incorrect. か Incorrect data. が適切だと思うけどどうだろ

2021-07-20 02:50 UTC, closed without merging